### ISSUE TITLE
Will the code be released?

### ISSUE THREAD

**Issue by DariaD** [ymcui/Interactive_AoA_Reader#1]
Dear Yiming, 

Will the code be released?
Also, seems like, the link to the institute website doesn't work.

Thank you in advance for your answer!

**Comment by ymcui** [comment]
Hi DariaD,
1. Unfortunately, the code is not available at the moment due to the company policy. We are managing publish the paper+code, but there is no guarantee.
2. Thank you for reporting. We have noticed that the link is not work outside China. We will fix this issue in future.
3. There are several features in our model which can be concluded as:
- Multiple hops for refining query-aware document representation and vice versa.
- Incorporating historical attention
- Combining various ensemble approaches for boosting ensemble performance
 These information has been revealed in a previous talk, http://ymcui.github.io/pdf/20171115_hkust_slides.pdf

Best,
Yiming

**Comment by DariaD** [comment]
Yiming, 

Thank you very much for your answer! 
Looking forward seeing the code and the article. Hope they will be released. 
Best, Daria
